# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=32, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=128, verbose_name='ApiUrl')),
                ('api_agreement', models.CharField(max_length=32, verbose_name='接口协议')),
                ('api_headers', models.CharField(max_length=128, verbose_name='请求头')),
            ],
            options={
                'verbose_name_plural': '接口表',
            },
        ),
        migrations.CreateModel(
            name='ObjManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目表')),
            ],
            options={
                'verbose_name_plural': '项目表',
            },
        ),
        migrations.CreateModel(
            name='ReqMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=32, verbose_name='请求方式')),
            ],
            options={
                'verbose_name_plural': '请求方式表',
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=32, verbose_name='模块名称')),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_main.ObjManage', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '模块表',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=32, verbose_name='用例名称')),
                ('case_prove', models.CharField(max_length=128, verbose_name='Key或者Cookie')),
                ('case_url', models.CharField(max_length=128, verbose_name='具体的请求URL路径')),
                ('case_parameter', models.CharField(max_length=128, verbose_name='请求参数')),
                ('case_expected_result', models.CharField(max_length=128, verbose_name='预期结果')),
                ('case_actual_results', models.CharField(max_length=128, verbose_name='实际结果')),
                ('case_api_headers', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_main.ApiRequest', verbose_name='接口表')),
                ('case_method_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_main.ReqMethod', verbose_name='请求方式')),
                ('case_module_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_main.Square', verbose_name='用例所属模块')),
            ],
            options={
                'verbose_name_plural': '测试案例表',
            },
        ),
        migrations.CreateModel(
            name='UserMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='apirequest',
            name='api_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_main.Square', verbose_name='接口所属模块'),
        ),
    ]
