# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('test_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermain',
            name='auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', verbose_name='用户权限'),
        ),
    ]
